export const COMMON_READER_ENTRIES = [
  { id: 'reader-helper-geu', hangul: '그', english: 'that / the', partOfSpeech: 'determiner' },
  { id: 'reader-helper-cheot', hangul: '첫', english: 'first', partOfSpeech: 'modifier' },
  { id: 'reader-helper-beonjjae', hangul: '번째', english: 'number / ordinal item', partOfSpeech: 'bound noun' },
  { id: 'reader-helper-nal', hangul: '날', english: 'day', partOfSpeech: 'noun' },
  { id: 'reader-helper-ttae', hangul: '때', english: 'time / when', partOfSpeech: 'noun' },
  { id: 'reader-helper-daeum', hangul: '다음', english: 'next', partOfSpeech: 'noun' },
  { id: 'reader-helper-jinan', hangul: '지난', english: 'last / past', partOfSpeech: 'modifier' },
  { id: 'reader-helper-ibeon', hangul: '이번', english: 'this time', partOfSpeech: 'noun' },
  { id: 'reader-helper-su', hangul: '수', english: 'way / possibility', partOfSpeech: 'bound noun' },
  { id: 'reader-helper-ssi', hangul: '씨', english: 'Mr. / Ms.', partOfSpeech: 'honorific suffix' },
  { id: 'reader-helper-jalmot', hangul: '잘못', english: 'mistake / wrongly', partOfSpeech: 'adverb' },
  { id: 'reader-helper-orae', hangul: '오래', english: 'for a long time', partOfSpeech: 'adverb' },
  { id: 'reader-helper-jjalda', hangul: '짧다', english: 'to be short', partOfSpeech: 'adjective' },
  { id: 'reader-helper-antda', hangul: '않다', english: 'not to be / not do', partOfSpeech: 'verb' },
  { id: 'reader-helper-itda', hangul: '있다', english: 'to exist / have', partOfSpeech: 'adjective' },
  { id: 'reader-helper-eopda', hangul: '없다', english: 'to not exist / not have', partOfSpeech: 'adjective' },
  { id: 'reader-helper-doeda', hangul: '되다', english: 'to become', partOfSpeech: 'verb' },
  { id: 'reader-helper-minsu', hangul: '민수', english: 'Minsu', partOfSpeech: 'name' },
  { id: 'reader-helper-sujin', hangul: '수진', english: 'Sujin', partOfSpeech: 'name' },
  { id: 'reader-helper-jimin', hangul: '지민', english: 'Jimin', partOfSpeech: 'name' },
  { id: 'reader-helper-geunal', hangul: '그날', english: 'that day', partOfSpeech: 'noun' },
  { id: 'reader-helper-ppeonhaesseoyo', hangul: '뻔했어요', english: 'almost did / nearly happened', partOfSpeech: 'grammar marker' },
  { id: 'reader-helper-annye', hangul: '안내', english: 'guide / information', partOfSpeech: 'noun' },
  { id: 'reader-helper-yennal', hangul: '옛날', english: 'old / former days', partOfSpeech: 'noun' },
  { id: 'reader-helper-dahaenghi', hangul: '다행히', english: 'fortunately', partOfSpeech: 'adverb' },
  { id: 'reader-helper-myeongjeol', hangul: '명절', english: 'holiday', partOfSpeech: 'noun' },
  { id: 'reader-helper-ingan', hangul: '인간', english: 'human', partOfSpeech: 'noun' },
  { id: 'reader-helper-setjjae', hangul: '셋째', english: 'third', partOfSpeech: 'noun' },
  { id: 'reader-helper-dansunhi', hangul: '단순히', english: 'simply', partOfSpeech: 'adverb' },
  { id: 'reader-helper-anira', hangul: '아니라', english: 'not A but', partOfSpeech: 'connector' },
  { id: 'reader-helper-budam', hangul: '부담', english: 'burden', partOfSpeech: 'noun' },
  { id: 'reader-helper-daek', hangul: '댁', english: 'home (honorific)', partOfSpeech: 'noun' },
  { id: 'reader-helper-timing', hangul: '타이밍', english: 'timing', partOfSpeech: 'noun' },
  { id: 'reader-helper-eoreun', hangul: '어른', english: 'adult / elder', partOfSpeech: 'noun' },
  { id: 'reader-helper-gamsahada', hangul: '감사하다', english: 'to be thankful', partOfSpeech: 'verb' },
  { id: 'reader-helper-nyuseu', hangul: '뉴스', english: 'news', partOfSpeech: 'noun' },
  { id: 'reader-helper-daneojang', hangul: '단어장', english: 'vocabulary list', partOfSpeech: 'noun' },
  { id: 'reader-helper-pyeonriham', hangul: '편리함', english: 'convenience', partOfSpeech: 'noun' },
  { id: 'reader-helper-gyeolgwa', hangul: '결과', english: 'result', partOfSpeech: 'noun' },
  { id: 'reader-helper-mesiji', hangul: '메시지', english: 'message', partOfSpeech: 'noun' },
  { id: 'reader-helper-yeongsang', hangul: '영상', english: 'video', partOfSpeech: 'noun' },
  { id: 'reader-helper-munmaek', hangul: '문맥', english: 'context', partOfSpeech: 'noun' },
  { id: 'reader-helper-gwanseup', hangul: '관점', english: 'perspective', partOfSpeech: 'noun' },
  { id: 'reader-helper-gonggan', hangul: '공간', english: 'space', partOfSpeech: 'noun' },
  { id: 'reader-helper-bae-gyeong', hangul: '배경', english: 'background', partOfSpeech: 'noun' },
  { id: 'reader-helper-juingong', hangul: '주인공', english: 'main character', partOfSpeech: 'noun' },
  { id: 'reader-helper-seontaek', hangul: '선택', english: 'choice', partOfSpeech: 'noun' },
  { id: 'reader-helper-bang-song', hangul: '방송', english: 'announcement / broadcast', partOfSpeech: 'noun' },
  { id: 'reader-helper-binjari', hangul: '빈자리', english: 'empty seat', partOfSpeech: 'noun' },
  { id: 'reader-helper-balmil', hangul: '발밑', english: 'under the feet', partOfSpeech: 'noun' },
  { id: 'reader-helper-geomda', hangul: '검다', english: 'to be black', partOfSpeech: 'adjective' },
  { id: 'reader-helper-namja', hangul: '남자', english: 'man', partOfSpeech: 'noun' },
  { id: 'reader-helper-hakseup', hangul: '학습', english: 'learning', partOfSpeech: 'noun' },
  { id: 'reader-helper-koneo', hangul: '코너', english: 'corner / column', partOfSpeech: 'noun' },
  { id: 'reader-helper-oegugin', hangul: '외국인', english: 'foreigner', partOfSpeech: 'noun' },
  { id: 'reader-helper-chogeup', hangul: '초급', english: 'beginner level', partOfSpeech: 'noun' },
  { id: 'reader-helper-junggeup', hangul: '중급', english: 'intermediate level', partOfSpeech: 'noun' },
  { id: 'reader-helper-neungnyeok', hangul: '능력', english: 'ability', partOfSpeech: 'noun' },
  { id: 'reader-helper-apateu', hangul: '아파트', english: 'apartment', partOfSpeech: 'noun' },
  { id: 'reader-helper-jumin', hangul: '주민', english: 'resident', partOfSpeech: 'noun' },
  { id: 'reader-helper-charyang', hangul: '차량', english: 'vehicle', partOfSpeech: 'noun' },
  { id: 'reader-helper-churip', hangul: '출입', english: 'entry and exit', partOfSpeech: 'noun' },
  { id: 'reader-helper-hyeopjo', hangul: '협조', english: 'cooperation', partOfSpeech: 'noun' },
  { id: 'reader-helper-gyeoksik', hangul: '격식', english: 'formality', partOfSpeech: 'noun' },
  { id: 'reader-helper-sangja', hangul: '상자', english: 'box', partOfSpeech: 'noun' },
  { id: 'reader-helper-tonghaeng', hangul: '통행', english: 'passage', partOfSpeech: 'noun' },
  { id: 'reader-helper-yeoreobun', hangul: '여러분', english: 'everyone', partOfSpeech: 'pronoun' },
  { id: 'reader-helper-gongjimun', hangul: '공지문', english: 'formal notice text', partOfSpeech: 'noun' },
  { id: 'reader-helper-yeolhan', hangul: '열한', english: 'eleven', partOfSpeech: 'number' },
  { id: 'reader-helper-buteuda', hangul: '붙다', english: 'to be posted / attached', partOfSpeech: 'verb' },
  { id: 'reader-helper-idonghada', hangul: '이동하다', english: 'to move', partOfSpeech: 'verb' },
  { id: 'reader-helper-jinhaengdoeda', hangul: '진행되다', english: 'to proceed / take place', partOfSpeech: 'verb' },
  { id: 'reader-helper-hyeopjohada', hangul: '협조하다', english: 'to cooperate', partOfSpeech: 'verb' },
  { id: 'reader-helper-samgada', hangul: '삼가다', english: 'to refrain', partOfSpeech: 'verb' },
  { id: 'reader-helper-jangso', hangul: '장소', english: 'place', partOfSpeech: 'noun' },
  { id: 'reader-helper-yecheukhada', hangul: '예측하다', english: 'to predict', partOfSpeech: 'verb' },
  { id: 'reader-helper-heungmiropda', hangul: '흥미롭다', english: 'to be interesting', partOfSpeech: 'adjective' },
  { id: 'reader-helper-toegeungil', hangul: '퇴근길', english: 'commute home', partOfSpeech: 'noun' },
  { id: 'reader-helper-gakja', hangul: '각자', english: 'each person', partOfSpeech: 'pronoun' },
  { id: 'reader-helper-josimhi', hangul: '조심히', english: 'carefully', partOfSpeech: 'adverb' },
  { id: 'reader-helper-daesin', hangul: '대신', english: 'instead', partOfSpeech: 'adverb' },
  { id: 'reader-helper-jikjeon', hangul: '직전', english: 'right before', partOfSpeech: 'noun' },
  { id: 'reader-helper-nyeon', hangul: '년', english: 'year', partOfSpeech: 'bound noun' },
  { id: 'reader-helper-dap', hangul: '답', english: 'answer', partOfSpeech: 'noun' },
  { id: 'reader-helper-jilmun', hangul: '질문', english: 'question', partOfSpeech: 'noun' },
  { id: 'reader-helper-sonan', hangul: '손안', english: 'in the hand', partOfSpeech: 'noun' },
  { id: 'reader-helper-anida', hangul: '아니다', english: 'to not be', partOfSpeech: 'adjective' },
  { id: 'reader-helper-banghaehada', hangul: '방해하다', english: 'to disturb', partOfSpeech: 'verb' },
  { id: 'reader-helper-ssahida', hangul: '쌓이다', english: 'to pile up', partOfSpeech: 'verb' },
  { id: 'reader-helper-pigonhaejida', hangul: '피곤해지다', english: 'to become tired', partOfSpeech: 'verb' },
  { id: 'reader-helper-sonjilhada', hangul: '손질하다', english: 'to prepare / trim', partOfSpeech: 'verb' },
  { id: 'reader-helper-gwailgap', hangul: '과일값', english: 'fruit price', partOfSpeech: 'noun' },
  { id: 'reader-helper-hankkeobeone', hangul: '한꺼번에', english: 'all at once', partOfSpeech: 'adverb' },
  { id: 'reader-helper-junggan', hangul: '중간', english: 'middle', partOfSpeech: 'noun' },
  { id: 'reader-helper-eoryeoum', hangul: '어려움', english: 'difficulty', partOfSpeech: 'noun' },
  { id: 'reader-helper-meomchuda', hangul: '멈추다', english: 'to stop', partOfSpeech: 'verb' },
  { id: 'reader-helper-jeonhyeongjeok', hangul: '전형적', english: 'typical', partOfSpeech: 'noun' },
  { id: 'reader-helper-daesang', hangul: '대상', english: 'target / audience', partOfSpeech: 'noun' },
  { id: 'reader-helper-jikjeop', hangul: '직접', english: 'directly', partOfSpeech: 'adverb' },
  { id: 'reader-helper-myeongnyeong', hangul: '명령', english: 'command', partOfSpeech: 'noun' },
  { id: 'reader-helper-hasipsioche', hangul: '하십시오체', english: 'formal polite speech style', partOfSpeech: 'noun' },
  { id: 'reader-helper-tteut', hangul: '뜻', english: 'meaning', partOfSpeech: 'noun' },
  { id: 'reader-helper-pyohyeon', hangul: '표현', english: 'expression', partOfSpeech: 'noun' },
  { id: 'reader-helper-haengdong', hangul: '행동', english: 'action', partOfSpeech: 'noun' },
  { id: 'reader-helper-dong', hangul: '동', english: 'apartment building', partOfSpeech: 'noun' },
  { id: 'reader-helper-nopida', hangul: '높이다', english: 'to raise / honor', partOfSpeech: 'verb' },
  { id: 'reader-helper-hanjia', hangul: '한지아', english: 'Han Jia', partOfSpeech: 'name' },
  { id: 'reader-helper-hanmadi', hangul: '한마디', english: 'one phrase / one word', partOfSpeech: 'noun' },
  { id: 'reader-helper-bujokham', hangul: '부족함', english: 'lack / insufficiency', partOfSpeech: 'noun' },
  { id: 'reader-helper-sinho', hangul: '신호', english: 'signal', partOfSpeech: 'noun' },
  { id: 'reader-helper-bigyohada', hangul: '비교하다', english: 'to compare', partOfSpeech: 'verb' },
  { id: 'reader-helper-nopajida', hangul: '높아지다', english: 'to become higher', partOfSpeech: 'verb' },
  { id: 'reader-helper-munbeop', hangul: '문법', english: 'grammar', partOfSpeech: 'noun' },
  { id: 'reader-helper-siljero', hangul: '실제로', english: 'actually / in practice', partOfSpeech: 'adverb' },
  { id: 'reader-helper-jayeonseureopda', hangul: '자연스럽다', english: 'to be natural', partOfSpeech: 'adjective' },
  { id: 'reader-helper-hwaginhada', hangul: '확인하다', english: 'to check / confirm', partOfSpeech: 'verb' },
  { id: 'reader-helper-neomda', hangul: '넘다', english: 'to exceed / pass', partOfSpeech: 'verb' },
  { id: 'reader-helper-yoguhada', hangul: '요구하다', english: 'to request / demand', partOfSpeech: 'verb' },
];
