export const ORIENTATION_CARDS = [
  {
    id: 'hangul-is-an-alphabet',
    title: 'Hangul is an alphabet',
    body: 'Korean writing is sound-based, not picture-based. You combine letters into blocks, so a block like 한 still has smaller sound pieces inside it.',
    exampleKo: 'ㅎ + ㅏ + ㄴ = 한',
    romanization: 'h + a + n = han',
    exampleEn: 'Letters combine into one syllable block.',
    chapterNumber: 1,
    chapterId: 'chapter-01',
  },
  {
    id: 'verbs-end-sentences',
    title: 'Verbs come at the end',
    body: 'Korean often feels like “I pizza eat.” The final verb or adjective carries the main action, tense, and politeness.',
    exampleKo: '저는 피자를 먹어요.',
    romanization: 'jeoneun pijareul meogeoyo.',
    exampleEn: 'I eat pizza.',
    chapterNumber: 5,
    chapterId: 'chapter-05',
  },
  {
    id: 'particles-mark-roles',
    title: 'Particles mark roles',
    body: 'Small endings after nouns show what each word is doing. English leans on word order; Korean uses particles like 은/는 and 을/를.',
    exampleKo: '저는 물을 마셔요.',
    romanization: 'jeoneun mureul masyeoyo.',
    exampleEn: 'I drink water.',
    chapterNumber: 3,
    chapterId: 'chapter-03',
  },
  {
    id: 'verbs-do-not-change-by-person',
    title: 'Verbs do not change by person',
    body: 'I, you, and he can all use the same verb form. The change you notice is usually tense, politeness, or sentence mood.',
    exampleKo: '저도 먹어요. 민수 씨도 먹어요.',
    romanization: 'jeodo meogeoyo. minsu ssido meogeoyo.',
    exampleEn: 'I eat too. Minsu eats too.',
    chapterNumber: 5,
    chapterId: 'chapter-05',
  },
  {
    id: 'politeness-is-clothing',
    title: 'Politeness is clothing for the same idea',
    body: 'The same message can wear different levels of politeness. This app uses 해요체 first because it is polite, common, and safe with strangers.',
    exampleKo: '감사합니다. / 고마워요. / 고마워.',
    romanization: 'gamsahamnida. / gomawoyo. / gomawo.',
    exampleEn: 'Thank you, in different social clothes.',
    chapterNumber: 40,
    chapterId: 'chapter-40',
  },
  {
    id: 'no-articles-or-required-plurals',
    title: 'No a, the, or required plural endings',
    body: 'Korean does not force you to choose a/the or add -s every time. Context usually tells people whether you mean one thing or several.',
    exampleKo: '사과 주세요.',
    romanization: 'sagwa juseyo.',
    exampleEn: 'Please give me an apple / apples.',
    chapterNumber: 3,
    chapterId: 'chapter-03',
  },
  {
    id: 'questions-can-be-intonation',
    title: 'Questions can be intonation',
    body: 'You do not flip the word order to ask a question. Often the sentence is the same, and your voice rises at the end.',
    exampleKo: '학생이에요. / 학생이에요?',
    romanization: 'haksaeng-ieyo. / haksaeng-ieyo?',
    exampleEn: 'It is “student.” / Are you a student?',
    chapterNumber: 3,
    chapterId: 'chapter-03',
  },
  {
    id: 'subjects-drop-often',
    title: 'Subjects drop when context is clear',
    body: 'Korean often leaves out “I” or “you” when everyone already knows who is being talked about. This is normal, not incomplete.',
    exampleKo: '괜찮아요.',
    romanization: 'gwaenchanayo.',
    exampleEn: 'I am okay. / It is okay. / No, thank you.',
    chapterNumber: 2,
    chapterId: 'chapter-02',
  },
  {
    id: 'two-number-systems',
    title: 'There are two number systems',
    body: 'Native Korean numbers count people, things, age, and clock hours. Sino-Korean numbers handle dates, money, minutes, phone numbers, and addresses.',
    exampleKo: '세 시 삼십 분',
    romanization: 'se si samsip bun',
    exampleEn: '3:30',
    chapterNumber: 15,
    chapterId: 'chapter-15',
  },
  {
    id: 'writing-and-sound-can-shift',
    title: 'Writing and sound can shift a little',
    body: 'Korean spelling is stable, but real speech connects sounds across blocks. Do not panic when 한국어 sounds closer to 한구거.',
    exampleKo: '한국어',
    romanization: 'hangugeo',
    exampleEn: 'Korean language',
    chapterNumber: 31,
    chapterId: 'chapter-31',
  },
];

